state_labels = {0: 'Delhi', 1: 'Kerala', 2: 'Puducherry', 3: 'Tamil nadu'}
district_labels = {
    0: 'Alapuzha',
    1: 'Ariyalur',
    2: 'CAW',
    3: 'CENTRAL',
    4: 'CRIME BRANCH',
    5: 'Chennai',
    6: 'Chennai city',
    7: 'Chennai rly',
    8: 'Coimbatore',
    9: 'Coimbatore City',
    10: 'Crime Branch',
    11: 'Cuddalore',
    12: 'DELHI UT TOTAL',
    13: 'DWARKA',
    14: 'Dharmapuri',
    15: 'Dindigul',
    16: 'EAST',
    17: 'EOW',
    18: 'Ernakulam Commr.',
    19: 'Ernakulam Rural',
    20: 'Erode',
    21: 'G.R.P.(RLY)',
    22: 'GRP(RLY)',
    23: 'I.G.I. AIRPORT',
    24: 'IGI AIRPORT',
    25: 'Idukki',
    26: 'KARAIKAL',
    27: 'Kanchipuram',
    28: 'Kannur',
    29: 'Kanyakumari',
    30: 'Karaikal',
    31: 'Karur',
    32: 'Kasargod',
    33: 'Kollam',
    34: 'Kollam Commr',
    35: 'Kollam Commr.',
    36: 'Kollam Rural',
    37: 'Kottayam',
    38: 'Kozhikode Commr.',
    39: 'Kozhikode Rural',
    40: 'Krishnagiri',
    41: 'METRO',
    42: 'METRO RAIL',
    43: 'Madurai',
    44: 'Madurai City',
    45: 'Malappuram',
    46: 'NEW DELHI',
    47: 'NORTH',
    48: 'NORTH EAST',
    49: 'NORTH WEST',
    50: 'NORTH-EAST',
    51: 'NORTH-WEST',
    52: 'Nagapattinam',
    53: 'Namakkal',
    54: 'Nilgiris',
    55: 'OUTER',
    56: 'PONDICHERRY',
    57: 'PUDUCHERRY',
    58: 'Palakkad',
    59: 'Pathanamthitta',
    60: 'Perambalur',
    61: 'Puducherry',
    62: 'Pudukottai',
    63: 'RAILWAY',
    64: 'ROHINI',
    65: 'Railway Chennai',
    66: 'Railway Trichy',
    67: 'Railways',
    68: 'Ramnathapuram',
    69: 'S.T.F.',
    70: 'SHAHDARA',
    71: 'SOUTH',
    72: 'SOUTH WEST',
    73: 'SOUTH-EAST',
    74: 'SOUTH-WEST',
    75: 'SPL CELL',
    76: 'SPUWAC',
    77: 'STF',
    78: 'Salem',
    79: 'Salem City',
    80: 'Sivagangai',
    81: 'Thanjavur',
    82: 'Theni',
    83: 'Thirunelveli',
    84: 'Thirunelveli City',
    85: 'Thiruvallur',
    86: 'Thiruvannamalai',
    87: 'Thiruvarur',
    88: 'Thoothugudi',
    89: 'Thoothukudi',
    90: 'Thrissur',
    91: 'Thrissur Commr.',
    92: 'Thrissur Rural',
    93: 'Tiruppur',
    94: 'Tiruppur City',
    95: 'Trichy',
    96: 'Trichy City',
    97: 'Trichy rly',
    98: 'Trivandrum Commr.',
    99: 'Trivandrum Rural',
    100: 'Trivandrum commd',
    101: 'VIGILANCE',
    102: 'Vellore',
    103: 'Villupuram',
    104: 'Virudhunagar',
    105: 'WEST',
    106: 'Wayanadu',
    107: 'spl CELL'
}

